- game/Game.tscn
- haldric.csproj
- units/Unit.cs
- units/UnitRegistry.cs
Unit attributes are now retrievable via xpath.
---
As a side note, Godot.Dictionary does not work with <String, XmlDocument> either, so at least for now it seems safe to say that its implementation is generally broken.
> Use System.Xml for reading XML instead of Godot's XMLParser.

- game/Game.cs
- game/Game.tscn
- haldric.csproj
- units/UnitRegistry.cs
- units/Units.xsd
- units/config/elves-wood/Archer.xml
- units/config/elves-wood/Fighter.xml
- units/config/elves-wood/Scout.xml
- units/config/elves-wood/Shaman.xml
- units/config/ocrs/Archer.xml
- units/config/ocrs/Assassin.xml
- units/config/ocrs/Grunt.xml
- units/config/orcs/Archer.xml
- units/config/orcs/Assassin.xml
- units/config/orcs/Grunt.xml
- units/config/trolls/Troll-Whelp.xml
Currently checks that:
The unit's type contains only alphanumeric characters, spaces, or underscores
The unit's name is a valid string
The unit's hitpoints are a valid integer and >= 1
The unit's movement a a valid integer and >= 0
The unit's damage is a valid integer and >= 0
The unit's image path is a valid string
> Adds a validation schema to be used with unit XML.

- source/global/Loader.gd
small fix - now it fails at the expected point where the #todo errorhandling is. (on non existent or corrupt scenes)
> fix_string_error_in_load_scenario

- source/game/Game.gd
Fixed bug: When side changes it still showed available moves for unit of another side.
> Fixed not clearing available bug

- source/editor/Editor.gd
- source/scenario/map/Map.gd
- source/scenario/map/Transitions.gd
Hello,
here are two commits fixing two issues:
1. Open Map Editor and try to map any tile -> it crashes because Map.initialize() was never called so I've added call to it in Editor.gd
2. Mapping was painfully slow (especially when mapping many tiles with multiple single clicks) because every time tile was changed all cell transitions were updated - now only changed cell and it's neighbors are updated
preview - it still works and is faster (gif is speeded up but you can see that there is no lag):
I'd love to contribute more to haldric so if my help is needed just tell me.
> Map editor improvements

- source/game/Game.gd
Fixes bug when hovering mouse over unit in fog of war would cause unit panel to show field with this unit.
> Show unit in a unit panel only if it is visible to the player

- source/game/Game.gd
- source/interface/camera/WesnothCamera.gd
- source/interface/hud/HUD.tscn
- source/interface/hud/Minimap.gd
- source/interface/hud/Minimap.tscn
- source/interface/hud/MinimapAreaOfView.gd
- source/interface/hud/MinimapViewportContainer.gd
Hi this commit implements minimap in game view. Here is preview (well now minimap is aligned correctly but I did not bother to record another gif) https://gfycat.com/tenderwethog but I really ecourage you to build yourself and check it out.
**Features:**
- adds minimap that is another viewport of game world
- shows which area is currently visible with white rect on minimap
- clicking to particular point on minimap moves camera there
- dragging 'area of view' on minimap moves main camera too
- Minimap node is constructed in such a way that all it needs is to have viewport of main world passed and one signal from WesnothCamera connected (to know if user moves camera) so it is highly reusable
**Known issues**
- when main camera leaves the map area of view on minimap also leaves minimap which …
> Implement first version of minimap

- source/scenario/map/Transitions.gd
Hi,
this patch fixes regression that I have introduced in https://github.com/wesnoth/haldric/commit/a973f35dfe843931b7720caf8a4360bd9cfd8c08 - tiles transitions stopped showing in game scene. My changes aimed to update transitions only where it was needed when adding tile in map editor, however it only worked when new tiles were added to the map. In Game all tiles are added at scenario load so no transitions were updated at all - to fix I made a change to update all transitions during Transitions.gd initialization (previous optimization still works if new tiles are added to map).
Proof it works again:
> Fix lack of tiles transitions in game

- source/editor/Editor.gd
- source/editor/Editor.tscn
- source/game/Game.gd
- source/interface/hud/Minimap.gd
- source/interface/hud/Minimap.tscn
- source/interface/hud/MinimapAreaOfView.gd
- source/scenario/map/Map.gd
Hello, please review this PR that adds minimap to map editor. I am submitting two commits - one for changing structure of map editor to work with viewport and other for adding and fixing minimap
**Features:**
- minimap is now present and working in map editor:
- editor scene was refactored to work with viewport and is now more similar go game scene in that regard. Having viewport was required to have minimap working. New structure looks like this:
- minimap was issues with area of view positioning was resolved, also now real viewport size is used to determine size of area of view rectangle
**Know issues:**
- changing screen resolution or resizing game window will still break minimap
> Minimap in editor

- source/game/Game.gd
This solves issue when range of movement shown on map was not correctly updated after movement.
Before: https://gfycat.com/adolescentcleanhectorsdolphin
After: https://gfycat.com/mediumaccurategonolek
> Update shown unit range after move

- source/interface/hud/Minimap.tscn
Sets clip content on minimap so that are of view is not drawn outside minimap boundaries.
Thanks for bitron for suggestion
> Don't draw area of view outside of minimap

- data/units/undead/VampireBat.tscn
- source/unit/Attack.gd
- source/unit/Unit.gd
This solves issue when fighting and exp systems were not connected, now exp is granted to attacker at kill, formula for amount of exp is `killedUnitLevel * 8`. 
Also solves issue where unit level was not incremented on levelup.
Also solves issue where np was thrown when attacking unit with attack type that defending unit did not have.
Also solves bug where units with 0hp were not killed.
> Grants exp at unit kill

- graphics/shaders_visual/cell_highlight.tres
- source/game/Game.gd
- source/interface/hud/GameHUD.gd
- source/interface/hud/GameHUD.tscn
- source/interface/hud/RecruitmentPopup.gd
- source/interface/hud/RecruitmentPopup.tscn
- source/interface/hud/UnitPanel.gd
- source/interface/hud/UnitRecruitmentCard.gd
- source/interface/hud/UnitRecruitmentCard.tscn
- source/scenario/Scenario.gd
- source/scenario/Side.gd
- source/scenario/map/Location.gd
- source/scenario/map/Map.gd
- source/scenario/map/Map.tscn
Hello, this is PR that implements basic recruitment mechanic. It is basic version of mechanic and some things are hardcoded, gui is very minimalistic, but well, it works and can be improved upon, which I will gladly do in later PRs. 
Closes part of  #58
1. When any unit (no idea of leader is present yet) steps on terrain that has recruit_from set to true (such as a keep), recruit button appears in some random place in HUD, tbd how it will look finally.
As discussed on discord we are not going to go for context menu for now (or at all)
2. Then when button is clicked list of units for recruitment is presented in popup:
Popup is made bigger to facilitate unit summary that probably will be part of this view (as in wesnoth)
3. When unit from the list is selected game moves into 'location …
> Implements basic recruitment

- source/game/Game.gd
Previously when unit was halted path fo field player was hoovering was not displayed. Player needed to make any mouse input (like move) to display the path which felt quite weird. Now this path is visible immediately after halting.
> Show move path after halting unit

- data/scenarios/test.gd
- source/game/Game.gd
- source/scenario/Scenario.gd
- source/scenario/Side.gd
- source/unit/Unit.gd
Hi,
with this PR only units marked as leaders will be able to recruit units (being leader is hardcoded in scenario startup script). I've changed concept a bit, I don't see a need for `Side` to keep array of all leaders since it keeps track of all units already. `Unit` can know if it is a leader and if `Side` needs to know it's leaders in future it can iterate over units. Having separate array on side creates issue of keeping list of units and array in sync. When leader is killed it was not removed from array of leaders (null is there instead) - before dying `Unit` would need to send signal to `Side` to remove it from array of leaders and only then `queue_free` could be called on `Unit`. Even then I think it is cleaner when unit encapsulates its whole state. If you don't like this change I …
> Reserve recruitment action only for leaders

- data/factions/rebels.tres
- data/scenarios/test.gd
- data/scenarios/test.tscn
- data/schedules/two_suns.tres
- graphics/shaders_visual/cell_highlight.tres
- source/game/Game.gd
- source/global/Registry.gd
- source/interface/hud/GameHUD.gd
- source/interface/hud/RecruitmentPopup.gd
- source/interface/hud/UnitRecruitmentCard.gd
- source/scenario/Side.gd
This PR brings some changes in area of recruitment. 
1) Now scenario config file has property sides with sides configured in dict. There is no separate side resource. Sides are no longer hardcoded and are loaded from that file dynamically.
2) Part of the side configuration is faction - all recruitable units of side are now taken from faction config.
3) Removed duplicated variable to hold recruitable units in `Side` class (did not notice previous one, it was unused anyways).
4) Now just string id of `unit_type` is passed around between recruitment popups and game. If needed actual `UnitType` object is taken from registry.
> Allow loading factions, sides and recruitment data from config. Slightly refactor recruitment code

- source/game/Game.gd
Quickfix for issue mentioned in https://github.com/wesnoth/haldric/issues/113, he reason is probably stronger type checking in newer version of godot
> Fixes case when code tried to assign null to vector3

- project.godot
- source/editor/Editor.gd
- source/editor/EditorHUD.gd
- source/editor/EditorHUD.tscn
After refactoring HUD signals from editor buttons were not connected - they were probably connected via scene config before. Here I connect them in code and do minor cleanup.
Saving and loading map is still broken but at least actions run as previously now.
I think that this PR proves that we should do connecting signals in code so that it is not lost during refactoring of scenes
> Connect editor buttons to actions again after refactor

- source/interface/hud/UnitRecruitmentCard.gd
wrong type was assigned to variable of type `PackedScene`, we were actually assigning `Node2D` there. Godot 3.2 actually checks that, previous version didn't
Fixes https://github.com/wesnoth/haldric/issues/115
> Fixes typing issue in recruitment code

- project.godot
- source/unit/Unit.gd
Instead of the line on line 103:
`	attacker.experience_current = type.level * 8`
which sets (kill xp = killed unit's level * 8), and makes it impossible to level up.
I replaced it with 
`	attacker.experience_current += type.level * 8`
> Fix bug that sets (kill xp = killed unit's level * 8), instead adding

- source/interface/hud/UnitPanel.gd
While I was testing Haldric, I noticed that the colors of the health bar in the side panel... didn't look too good. This is caused by the fact that a simple RGB calculation usually doesn't produce decent results.
This PR replaces the RGB calculations in `_get_red_to_green_color()` with a relative ratio, which in turn is used to pick a color for the health bar (or anything else that might need it, like terrain defense labels). The five colors used here are green, lime, yellow, orange and red. The attached picture shows the final result.
> Refactored _get_red_to_green_color function

- project.godot
- source/game/Game.gd
- source/game/Game.tscn
- source/game/ui/GameUI.gd
- source/game/ui/GameUI.tscn
- source/interface/hud/AttackPopup.tscn
- source/interface/hud/UnitPlate.gd
- source/interface/hud/UnitPlate.tscn
- source/scenario/Scenario.gd
- source/unit/Unit.gd
- source/unit/Unit.tscn
1. as requested in https://github.com/wesnoth/haldric/issues/67 `UnitPlate` is now separate node managed by `GameUI`
2. `Unit` has remote transform that allows `UnitPlate` to follow moving `Unit`
3. `Unit` communicates with `UnitPlate` only with signals. They only know about each other through remote transform and during initialization (to wire-up signals and set transform reference)
4. `GameHUD` and `GameUI` have been splitted, there was an issue when HUD was attempting to draw viewport it was part of in separate viewports (minimap, unit view)
> Decouple unit UI from unit

- source/interface/editor/EditorUI.gd
- source/interface/editor/EditorUI.tscn
Simple update made to prevent crashes and get familiarized with the project architecture before making further contributions.
I'm willing to add also a dialog to save and load map files onto the editor once I have time. Let me know of any changes needed in this PR.
> Validate map size before enabling creation

- data/scenarios/MiniScenario2.tscn
- data/scenarios/mini_scenario2.tres
- project.godot
- source/game/Game.gd
- source/interface/game/UnitPlate.tscn
- source/interface/game/UnitUI.tscn
- source/menu/TitleScreen.tscn
- source/scenario/Scenario.gd
- source/unit/Unit.gd
Previously, movement was not visible for other sides if the previous player already ended their turn. This PR refreshes units at the end of their turn.
> refresh units on turn end, makes movement visible for other sides too
